version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: shiphero_app
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - ENV
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUGGER
      - DEBUGGER_PORT
      - MONGODB_HOST=0.0.0.0
      - MONGODB_USER=root
      - MONGODB_PASS=toor
      - MONGODB_DB=shiphero
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      shiphero:
        aliases:
          - shiphero-app
    command: python3 run.py --host=0.0.0.0 --port=8080
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: shiphero
    volumes:
      - shiphero-data:/data/db
    networks:
      shiphero:
        aliases:
          - shiphero-mongo

networks:
  shiphero:
    driver: "bridge"

volumes:
  shiphero-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
