version: '3.4'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: side_stacker_backend
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
      - PYTHONUNBUFFERED=0
      - ENV
      - MONGODB_HOST=0.0.0.0
      - MONGODB_USER=root
      - MONGODB_PASS=toor
      - MONGODB_DB=sidestacker
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    networks:
      side_stacker_network:
        aliases:
          - side-stacker-network
    command: python3 src/side_stacker/sanic_app.py
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: side_stacker_frontend
    environment:
      - ENV
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    # command: python3 src/side_stacker/sanic_app.py
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: sidestacker
    volumes:
      - side-stacker-data:/data/db
    networks:
      side_stacker_network:
        aliases:
          - side-stacker-mongo

networks:
  side_stacker_network:
    driver: "bridge"

volumes:
  side-stacker-data:
    driver_opts:
      type: tmpfs
      device: tmpfs
