export const BOARD_ROWS = 7;
export const BOARD_COLUMNS = 7;
export const SIDE_LEFT = "L"; // reflects backend
export const SIDE_RIGHT = "R"; // reflects backend
export const SIDES = [SIDE_LEFT, SIDE_RIGHT] as const;
export const EMPTY_CELL = null;
export const PLAYER_COLOR_RED = "red"; // reflects backend
export const PLAYER_COLOR_YELLOW = "yellow"; // reflects backend
export const PLAYER_COLORS = [PLAYER_COLOR_RED, PLAYER_COLOR_YELLOW] as const;
export const EVENT_TYPE_WIN = "win"; // reflects backend
export const EVENT_TYPE_PLAY= "play"; // reflects backend
export const EVENT_TYPE_ERROR = "error"; // reflects backend
export const EVENT_TYPES = [EVENT_TYPE_PLAY, EVENT_TYPE_WIN, EVENT_TYPE_ERROR] as const;